enabled: true
content: |-
  cv:
    name: "Mehdi Yazdani-Jahromi"
    location: "Orlando, FL"
    email: "yazdani@ucf.edu"
    phone: "tel:+1-407-810-4467"
    website: "http://yazdanimehdi.com"
    social_networks:
      - network: "LinkedIn"
        username: "yazdanimehdi"
      - network: "GitHub"
        username: "yazdanimehdi"
    sections:
      summary:
        - "AI research scientist and PhD in Computer Science specializing in representation learning, with primary applications in computational biology and drug discovery. Industry experience at Johnson and Johnson and Microsoft, where I developed language models for mRNA and machine learning systems for large scale biomedical data. Strong programming background in Python, and JavaScript, with deep experience in PyTorch, Transformers and graph neural networks. Published in NeurIPS, ICLR and Briefings in Bioinformatics, with work spanning mRNA modeling, drug target interaction prediction and algorithmic fairness."

      skills:
        - label: "Programming Languages"
          details: "Python, Dart, JavaScript, C++, C#, SQL, Solidity, MATLAB"
        - label: "Python Packages"
          details: "Pytorch, Numpy, Pandas, Keras, TensorFlow, Scikit-learn, Scipy, Networkx, iGraph, dgl, matplotlib, seaborn"
        - label: "JavaScript Frameworks"
          details: "Vue.js, Electron, NativeScript"
        - label: "Tools"
          details: "Kubernetes, Docker, Git, HTML, CSS, LATEX, AWS, Azure, Slurm"
        - label: "Quantitative Research"
          details: "Machine Learning Methods, Artificial Intelligence, Large Language Models, Generative AI, Genomics Sequence Modeling, Drug Discovery, Graph Neural Networks, Transformers, Recurrent Neural Networks, LSTMs, Mathematical Optimization, Mathematical Modeling"
        - label: "Soft Skills"
          details: "Research team coordination, Student mentoring, Technical writing, Conference presentations, Resource allocation, Strategic planning, Analytical thinking, Complex problem resolution, International team collaboration, Multicultural communication, Self-directed learning, Professional networking"

      education:
        - institution: "University of Central Florida"
          area: "Computer Science"
          degree: "PhD"
          start_date: 2021-01
          end_date: 2025-10
          highlights:
            - "Thesis: Advancing Drug Discovery with Structural and Representation Learning of Biological Systems [Link](https://stars.library.ucf.edu/etd2024/515/)"
            - "GPA: 3.91/4.0"
        - institution: "University of Central Florida"
          area: "Computer Science"
          degree: "MS"
          start_date: 2021-01
          end_date: 2023-08
          highlights:
            - "GPA: 3.9/4.0"
        - institution: "Sharif University of Technology"
          area: "Industrial Engineering"
          degree: "MS"
          start_date: 2017-09
          end_date: 2019-12
          highlights:
            - "GPA: 3.88/4.0"

      research_experience:

        - company: "University of Central Florida"
          position: "Graduate Research Assistant"
          location: "Orlando, FL"
          start_date: 2021-08
          end_date: "2025-12"
          highlights:
            - Conducted advanced research in computational drug discovery, focusing on drug-target interaction and algorithmic fairness.
            - Developed and implemented machine learning models, including Transformers and Graph Neural Networks, for computer vision applications.
            - Collaborated on multiple interdisciplinary projects, contributing to the advancement of AI methodologies in drug discovery.
            - Published research findings in reputable journals and presented them at international conferences.
            - Utilized tools such as Pytorch, TensorFlow, and Scikit-learn to develop and evaluate innovative algorithms.
            - Engaged in data analysis and model optimization to enhance prediction accuracy and computational efficiency.
            - Assisted in mentoring undergraduate and graduate students and contributed to the academic community through collaborative efforts and knowledge-sharing sessions.

        - company: "Microsoft"
          position: "Research Intern, Bio-LLMs"
          location: "Redmond, WA"
          start_date: "2025-06"
          end_date: "2025-09"
          highlights:
            - "Built a novel agent orchestration system for planning, tool use, and judgment."
            - "Explored agentic AI on deidentified clinical datasets with end to end experiments and evaluation."
            - "Developed a RAG retrieval stack with hybrid dense and sparse search, reranking, and citation attribution."
            - "Contributed to the development of evaluation metrics and benchmarks for agentic AI systems."
        # - company: Asarad
        #   position: "Principal AI Scientist"
        #   location: "Remote"
        #   start_date: "2022-02"
        #   end_date: "present"
        #   # highlights:
        #   #   -

        - company: "Johnson & Johnson (Janssen R&D)"
          position: "Data Science Intern, AI/ML for Drug Discovery"
          start_date: 2024-05
          end_date: 2024-11
          highlights:
            - Developed and trained HELM (Hierarchical Encoding for mRNA Language Modeling), the first mRNA antibody language model, achieving up to 8% increase in prediction accuracy and enabling the generation of more diverse and biologically plausible sequences.
            - Explored alternative attention architectures such as Mamba and Hyena, enhancing transformer model efficiency and effectiveness in processing mRNA sequences.
            - Implemented large-scale distributed training on Kubernetes, resulting in significant reduction in training time for LLMs on extensive datasets, optimizing resource utilization and scalability.
            - Collaborated with cross-functional teams to refine and deploy advanced LLM architectures, enhancing model accuracy and efficiency for large-scale data processing tasks.

      selected_publications:
        - title: "Equi-mRNA: Protein Translation Equivariant Encoding for mRNA Language Models"
          authors: ["**Mehdi Yazdani-Jahromi**", "Ali Khodabandeh Yalabadi", "Ozlem Ozmen Garibay"]
          journal: "Neurips 2025"
          date: 2025
          doi: 10.48550/arXiv.2508.15103

        - title: "BoKDiff: Best-of-K Diffusion Alignment for Target-Specific 3D Molecule Generation"
          authors: ["Ali Khodabandeh Yalabadi", "**Mehdi Yazdani-Jahromi**", "Ozlem Ozmen Garibay"]
          journal: "Advances in Bioinformatics"
          date: 2025
          doi: 10.48550/arXiv.2501.15631

        - title: "HELM: Hierarchical Encoding for mRNA Language Modeling"
          authors: ["**Mehdi Yazdani-Jahromi**", "Mangal Prakash", "Tommaso Mansi", "Artem Moskalev", "Rui Liao"]
          journal: "ICLR 2025, Neurips 2024 Workshop on AI for New Drug Modalities"
          date: 2024
          doi: 10.48550/arXiv.2410.12459

        - title: "Fair Bilevel Neural Network (FairBiNN): On Balancing fairness and accuracy via Stackelberg Equilibrium"
          authors: ["**Mehdi Yazdani-Jahromi**", "Ali Khodabandeh Yalabadi", "AmirArsalan Rajabi", "Aida Tayebi", "Ivan Garibay", "Ozlem Ozmen Garibay"]
          journal: "Neurips 2024"
          date: "2024"
          doi: 10.48550/arXiv.2410.16432

        - title: "Learning Fair Representations: Mitigating Statistical Dependencies"
          authors: ["Aida Tayebi", "**Mehdi Yazdani-Jahromi**", "Ali Khodabandeh Yalabadi", "Niloofar Yousefi", "Ozlem Ozmen Garibay"]
          journal: "HCII conference 2023 Oral Presentation"
          date: "2024"
          doi: 10.1007/978-3-031-60611-3_8

        - title: "FragXsiteDTI: an interpretable transformer-based model for drug-target interaction prediction"
          authors: ["Ali Khodabandeh Yalabadi", "**Mehdi Yazdani-Jahromi**", "Niloofar Yousefi", "Aida Tayebi", "Sina Abdidizaji", "Ozlem Ozmen Garibay"]
          journal: "Recomb 2024 (Oral), Neurips 2023 Workshop on New Frontiers of AI for Drug Discovery and Development"
          date: "2024"
          doi: 10.1007/978-1-0716-3989-4_5

        - title: "Controlling the misinformation diffusion in social media by the effect of different classes of agents"
          authors: ["Ali Khodabandeh Yalabadi", "Mehdi Yazdani-Jahromi", "Sina Abdidizaji", "Ivan Garibay", "Ozlem Ozmen Garibay"]
          journal: "The Computational Social Science Society of the Americas Annual Conference"
          date: "2023"
          doi: 10.48550/arXiv.2401.11524

        - title: "Agent-Based Modeling of C. Difficile Spread in Hospitals: Assessing Contribution of High-Touch vs. Low-Touch Surfaces and Inoculations' Containment Impact"
          authors: ["Sina Abdidizaji", "Ali Khodabandeh Yalabadi", "Mehdi Yazdani-Jahromi", "Ozlem Ozmen Garibay", "Ivan Garibay"]
          journal: "The Computational Social Science Society of the Americas Annual Conference"
          date: "2023"
          doi: 10.48550/arXiv.2401.11656

        - title: "Through a fair looking-glass: on mitigating bias in image datasets"
          authors: ["Amirarsalan Rajabi", "**Mehdi Yazdani-Jahromi**", "Ozlem Ozmen Garibay", "Gita Sukthankar"]
          journal: "HCII conference 2023 (Oral), AAAI 2023 Workshop on Representation Learning for Responsible Human-Centric AI"
          date: "2023"
          doi: 10.1007/978-3-031-35891-3_27

        - title: "BindingSiteAugmented DTA to enable A Next-Generation Pipeline for Interpretable Prediction Models in Drug-Repurposing"
          authors: ["Niloofar Yousefi", "**Mehdi Yazdani-Jahromi**", "Aida Tayebi", "Elayaraja Kolanthai", "Craig J Neal", "Tanumoy Banerjee", "Agnivo Gosai", "Ganesh Balasubramanian", "Sudipta Seal", "Ozlem Ozmen Garibay"]
          journal: "Briefings in Bioinformatics"
          date: "2023"
          doi: 10.1093/bib/bbad136

        - title: "AttentionSiteDTI: Attention Based Model for Predicting Drug-Target Interaction Using 3D Structure of Protein Binding Sites"
          authors: ["**Mehdi Yazdani-Jahromi**", "Niloofar Yousefi", "Aida Tayebi", "Elayaraja Kolanthai", "Craig J Neal", "Sudipta Seal", "Ozlem Ozmen Garibay"]
          journal: "Briefings in Bioinformatics"
          date: "2022"
          doi: 10.1093/bib/bbac272

        - title: "UnbiasedDTI: Mitigating Real-World Bias of Drug-Target Interaction Prediction"
          authors: ["Aida Tayebi", "Niloofar Yousefi", "**Mehdi Yazdani-Jahromi**", "Elayaraja Kolanthai", "Craig J Neal", "Sudipta Seal", "Ozlem Ozmen Garibay"]
          journal: "MDPI Molecules"
          date: "2022"
          doi: 10.3390/molecules27092980

      academic_services:
        - Reviewer of Journal Briefings in Bioinformatics
        - Reviewer of Computational and Structural Biotechnology Journal
        - Reviewer of IEEE Transactions on Neural Networks and Learning Systems Journal
        - Program Committee Member of AAAI Artificial Intelligence for Social Impact 2025 & 2026.
        - Reviewer of Neurips 2025 (The Thirty-Ninth Annual Conference on Neural Information Processing Systems)
