cv:
  email: yazdani@ucf.edu
  location: Orlando, FL
  name: Mehdi Yazdani-Jahromi
  phone: tel:+1-407-810-4467
  sections:
    academicServices:
    - Reviewer of Journal Briefings in Bioinformatics
    - Reviewer of Computational and Structural Biotechnology Journal
    - Reviewer of IEEE Transactions on Neural Networks and Learning Systems Journal
    - Program Committee Member of AAAI Artificial Intelligence for Social Impact 2025
      & 2026.
    - Reviewer of Neurips 2025 (The Thirty-Ninth Annual Conference on Neural Information
      Processing Systems)
    education:
    - area: Computer Science
      degree: PhD
      endDate: 2025-10
      highlights:
      - 'Thesis: Advancing Drug Discovery with Structural and Representation Learning
        of Biological Systems [Link](https://stars.library.ucf.edu/etd2024/515/)'
      - 'GPA: 3.91/4.0'
      institution: University of Central Florida
      startDate: 2021-01
    - area: Computer Science
      degree: MS
      endDate: 2023-08
      highlights:
      - 'GPA: 3.9/4.0'
      institution: University of Central Florida
      startDate: 2021-01
    - area: Industrial Engineering
      degree: MS
      endDate: 2019-12
      highlights:
      - 'GPA: 3.88/4.0'
      institution: Sharif University of Technology
      startDate: 2017-09
    researchExperience:
    - company: University of Central Florida
      endDate: 2025-12
      highlights:
      - Conducted advanced research in computational drug discovery, focusing on drug-target
        interaction and algorithmic fairness.
      - Developed and implemented machine learning models, including Transformers
        and Graph Neural Networks, for computer vision applications.
      - Collaborated on multiple interdisciplinary projects, contributing to the advancement
        of AI methodologies in drug discovery.
      - Published research findings in reputable journals and presented them at international
        conferences.
      - Utilized tools such as Pytorch, TensorFlow, and Scikit-learn to develop and
        evaluate innovative algorithms.
      - Engaged in data analysis and model optimization to enhance prediction accuracy
        and computational efficiency.
      - Assisted in mentoring undergraduate and graduate students and contributed
        to the academic community through collaborative efforts and knowledge-sharing
        sessions.
      location: Orlando, FL
      position: Graduate Research Assistant
      startDate: 2021-08
    - company: Microsoft
      endDate: 2025-09
      highlights:
      - Built a novel agent orchestration system for planning, tool use, and judgment.
      - Explored agentic AI on deidentified clinical datasets with end to end experiments
        and evaluation.
      - Developed a RAG retrieval stack with hybrid dense and sparse search, reranking,
        and citation attribution.
      - Contributed to the development of evaluation metrics and benchmarks for agentic
        AI systems.
      location: Redmond, WA
      position: Research Intern, Bio-LLMs
      startDate: 2025-06
    - company: Johnson & Johnson (Janssen R&D)
      endDate: 2024-11
      highlights:
      - Developed and trained HELM (Hierarchical Encoding for mRNA Language Modeling),
        the first mRNA antibody language model, achieving up to 8% increase in prediction
        accuracy and enabling the generation of more diverse and biologically plausible
        sequences.
      - Explored alternative attention architectures such as Mamba and Hyena, enhancing
        transformer model efficiency and effectiveness in processing mRNA sequences.
      - Implemented large-scale distributed training on Kubernetes, resulting in significant
        reduction in training time for LLMs on extensive datasets, optimizing resource
        utilization and scalability.
      - Collaborated with cross-functional teams to refine and deploy advanced LLM
        architectures, enhancing model accuracy and efficiency for large-scale data
        processing tasks.
      position: Data Science Intern, AI/ML for Drug Discovery
      startDate: 2024-05
    selectedPublications:
    - authors:
      - '**Mehdi Yazdani-Jahromi**'
      - Ali Khodabandeh Yalabadi
      - Ozlem Ozmen Garibay
      date: 2025
      doi: 10.48550/arXiv.2508.15103
      journal: Neurips 2025
      title: 'Equi-mRNA: Protein Translation Equivariant Encoding for mRNA Language
        Models'
    - authors:
      - Ali Khodabandeh Yalabadi
      - '**Mehdi Yazdani-Jahromi**'
      - Ozlem Ozmen Garibay
      date: 2025
      doi: 10.48550/arXiv.2501.15631
      journal: Advances in Bioinformatics
      title: 'BoKDiff: Best-of-K Diffusion Alignment for Target-Specific 3D Molecule
        Generation'
    - authors:
      - '**Mehdi Yazdani-Jahromi**'
      - Mangal Prakash
      - Tommaso Mansi
      - Artem Moskalev
      - Rui Liao
      date: 2024
      doi: 10.48550/arXiv.2410.12459
      journal: ICLR 2025, Neurips 2024 Workshop on AI for New Drug Modalities
      title: 'HELM: Hierarchical Encoding for mRNA Language Modeling'
    - authors:
      - '**Mehdi Yazdani-Jahromi**'
      - Ali Khodabandeh Yalabadi
      - AmirArsalan Rajabi
      - Aida Tayebi
      - Ivan Garibay
      - Ozlem Ozmen Garibay
      date: '2024'
      doi: 10.48550/arXiv.2410.16432
      journal: Neurips 2024
      title: 'Fair Bilevel Neural Network (FairBiNN): On Balancing fairness and accuracy
        via Stackelberg Equilibrium'
    - authors:
      - Aida Tayebi
      - '**Mehdi Yazdani-Jahromi**'
      - Ali Khodabandeh Yalabadi
      - Niloofar Yousefi
      - Ozlem Ozmen Garibay
      date: '2024'
      doi: 10.1007/978-3-031-60611-3_8
      journal: HCII conference 2023 Oral Presentation
      title: 'Learning Fair Representations: Mitigating Statistical Dependencies'
    - authors:
      - Ali Khodabandeh Yalabadi
      - '**Mehdi Yazdani-Jahromi**'
      - Niloofar Yousefi
      - Aida Tayebi
      - Sina Abdidizaji
      - Ozlem Ozmen Garibay
      date: '2024'
      doi: 10.1007/978-1-0716-3989-4_5
      journal: Recomb 2024 (Oral), Neurips 2023 Workshop on New Frontiers of AI for
        Drug Discovery and Development
      title: 'FragXsiteDTI: an interpretable transformer-based model for drug-target
        interaction prediction'
    - authors:
      - Ali Khodabandeh Yalabadi
      - Mehdi Yazdani-Jahromi
      - Sina Abdidizaji
      - Ivan Garibay
      - Ozlem Ozmen Garibay
      date: '2023'
      doi: 10.48550/arXiv.2401.11524
      journal: The Computational Social Science Society of the Americas Annual Conference
      title: Controlling the misinformation diffusion in social media by the effect
        of different classes of agents
    - authors:
      - Sina Abdidizaji
      - Ali Khodabandeh Yalabadi
      - Mehdi Yazdani-Jahromi
      - Ozlem Ozmen Garibay
      - Ivan Garibay
      date: '2023'
      doi: 10.48550/arXiv.2401.11656
      journal: The Computational Social Science Society of the Americas Annual Conference
      title: 'Agent-Based Modeling of C. Difficile Spread in Hospitals: Assessing
        Contribution of High-Touch vs. Low-Touch Surfaces and Inoculations'' Containment
        Impact'
    - authors:
      - Amirarsalan Rajabi
      - '**Mehdi Yazdani-Jahromi**'
      - Ozlem Ozmen Garibay
      - Gita Sukthankar
      date: '2023'
      doi: 10.1007/978-3-031-35891-3_27
      journal: HCII conference 2023 (Oral), AAAI 2023 Workshop on Representation Learning
        for Responsible Human-Centric AI
      title: 'Through a fair looking-glass: on mitigating bias in image datasets'
    - authors:
      - Niloofar Yousefi
      - '**Mehdi Yazdani-Jahromi**'
      - Aida Tayebi
      - Elayaraja Kolanthai
      - Craig J Neal
      - Tanumoy Banerjee
      - Agnivo Gosai
      - Ganesh Balasubramanian
      - Sudipta Seal
      - Ozlem Ozmen Garibay
      date: '2023'
      doi: 10.1093/bib/bbad136
      journal: Briefings in Bioinformatics
      title: BindingSiteAugmented DTA to enable A Next-Generation Pipeline for Interpretable
        Prediction Models in Drug-Repurposing
    - authors:
      - '**Mehdi Yazdani-Jahromi**'
      - Niloofar Yousefi
      - Aida Tayebi
      - Elayaraja Kolanthai
      - Craig J Neal
      - Sudipta Seal
      - Ozlem Ozmen Garibay
      date: '2022'
      doi: 10.1093/bib/bbac272
      journal: Briefings in Bioinformatics
      title: 'AttentionSiteDTI: Attention Based Model for Predicting Drug-Target Interaction
        Using 3D Structure of Protein Binding Sites'
    - authors:
      - Aida Tayebi
      - Niloofar Yousefi
      - '**Mehdi Yazdani-Jahromi**'
      - Elayaraja Kolanthai
      - Craig J Neal
      - Sudipta Seal
      - Ozlem Ozmen Garibay
      date: '2022'
      doi: 10.3390/molecules27092980
      journal: MDPI Molecules
      title: 'UnbiasedDTI: Mitigating Real-World Bias of Drug-Target Interaction Prediction'
    skills:
    - details: Python, Dart, JavaScript, C++, C#, SQL, Solidity, MATLAB
      label: Programming Languages
    - details: Pytorch, Numpy, Pandas, Keras, TensorFlow, Scikit-learn, Scipy, Networkx,
        iGraph, dgl, matplotlib, seaborn
      label: Python Packages
    - details: Vue.js, Electron, NativeScript
      label: JavaScript Frameworks
    - details: Kubernetes, Docker, Git, HTML, CSS, LATEX, AWS, Azure, Slurm
      label: Tools
    - details: Machine Learning Methods, Artificial Intelligence, Large Language Models,
        Generative AI, Genomics Sequence Modeling, Drug Discovery, Graph Neural Networks,
        Transformers, Recurrent Neural Networks, LSTMs, Mathematical Optimization,
        Mathematical Modeling
      label: Quantitative Research
    - details: Research team coordination, Student mentoring, Technical writing, Conference
        presentations, Resource allocation, Strategic planning, Analytical thinking,
        Complex problem resolution, International team collaboration, Multicultural
        communication, Self-directed learning, Professional networking
      label: Soft Skills
    summary:
    - AI research scientist and PhD in Computer Science specializing in representation
      learning, with primary applications in computational biology and drug discovery.
      Industry experience at Johnson and Johnson and Microsoft, where I developed
      language models for mRNA and machine learning systems for large scale biomedical
      data. Strong programming background in Python, and JavaScript, with deep experience
      in PyTorch, Transformers and graph neural networks. Published in NeurIPS, ICLR
      and Briefings in Bioinformatics, with work spanning mRNA modeling, drug target
      interaction prediction and algorithmic fairness.
  socialNetworks:
  - network: LinkedIn
    username: yazdanimehdi
  - network: GitHub
    username: yazdanimehdi
  website: http://yazdanimehdi.com
