mediumUrl: https://medium.com/feed/@myjahromi
feeds:
  - name: medium.com
    url: https://medium.com/feed/@myjahromi
    author: mehdi-yazdani-jahromi
    tags:
      - medium
syncInterval: daily
maxItemsPerFeed: 20
