description: |
  Graduate Research Assistant at the University of Central Florida.
areas:
  - title: AI
    description: ""
    tags:
      - AI
      - Artificial Intelligence
      - Transformers
  - title: Drug Discovery
    description: ""
    tags:
      - Drug Discovery
      - DTI
      - DTA
  - title: Fairness
    description: ""
    tags:
      - Fairness
